Branchfor task1
StrangerM/Homework pull request #1
Opened 2021-04-10 13:55 UTC by StrangerM

2021-04-10 17:04 UTC, yevhenbilushko reviewed
Test comment

2021-04-12 17:44 UTC, serhii-shkodenko requested changes
На перший погляд, все досить добре. Виправ, будь ласка, ці зауваження. Я ще завтра подивлюсь незамиленим оком.

2021-04-12 17:44 UTC, serhii-shkodenko commented on Task1/HomeWork.cs
> +            // Your solution supposed to be here.
Цей коментар можна видалити.

2021-04-12 17:44 UTC, serhii-shkodenko commented on Task1/HomeWork.cs
> +            if (destinations.Count() == clients.Count() && prices.Count() == currencies.Count())
Щоб знизити вкладеність коду, можна зробити щось на кшталт:
```
if(!(ValidationIsSuccsesfull()))
{
    return fullPrice;
}
for()
...
```
Тоді вкладеніть гілки з циклом `for` знизиться.

2021-04-12 17:44 UTC, serhii-shkodenko commented on Task1/HomeWork.cs
> +                    decimal waynStreet = destinations.ElementAt(x).Contains("Wayne Street") ? 10 : 0;
Для С# є типовим використовувати неявну типізацію змінних за допомогою `var`. Є навість [відповідна конвенція](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-12 17:44 UTC, serhii-shkodenko commented on Task1/HomeWork.cs
> +                    tempforInfants.ToList().Clear();
Щоб очистити змінну, можна було просто приcвоїти їй значення за замовченням (`default`). `ToList()` це не безкоштовна операція, тому нею користуватись, щоб отримати доступ до методу `Clear()`, не є повністю виправданим. Крім того, очищати змінні у .NET загалом немає потреби. За тебе це зробить Garbage Collector. Існують певні випадки, коли це треба робити самому, але ми про них поговоримо пізніше у наступних лекціях.

Цей код можна просто видалати.

2021-04-12 17:44 UTC, serhii-shkodenko commented on Task1/HomeWork.cs
> +                    tempforChildren.ToList().Clear();
Так само. Дивись вище.

2021-04-12 18:20 UTC, StrangerM commented on Task1/HomeWork.cs
> +            // Your solution supposed to be here.
Fixed

2021-04-12 18:20 UTC, StrangerM commented on Task1/HomeWork.cs
> +            if (destinations.Count() == clients.Count() && prices.Count() == currencies.Count())
Fixed

2021-04-12 18:20 UTC, StrangerM commented on Task1/HomeWork.cs
> +                    tempforInfants.ToList().Clear();
Fixed

2021-04-12 18:21 UTC, StrangerM commented on Task1/HomeWork.cs
> +                    tempforChildren.ToList().Clear();
Fixed

2021-04-13 05:24 UTC, StrangerM commented on Task1/HomeWork.cs
> +            if (destinations.Count() == clients.Count() && prices.Count() == currencies.Count())
if (destinations.Count() != clients.Count() && prices.Count() != currencies.Count())
            {
                return fullPrice;
            }

2021-04-13 05:25 UTC, StrangerM commented on Task1/HomeWork.cs
> +                    tempforInfants.ToList().Clear();
var tempforInfants = infantsIds.Where(y => y == x);
                    decimal discountForInfants = tempforInfants.Any() ? 0.5m : 1;

2021-04-16 10:12 UTC, serhii-shkodenko approved these changes
Понравилось, как сделано определение адресов с разными домами на одной улице. Замечение на будущее, старайся отделять логически связанные блоки кода пустыми строками. Можно мержить.

2021-04-16 10:54 UTC, merged