Task3 has done
StrangerM/Homework pull request #3
Opened 2021-04-21 16:42 UTC by StrangerM

was developed the possibility to add some restaurant, the restaurant can add any meal and meal could be bind with the restaurant by IdRestaurant.

2021-04-26 07:10 UTC, serhii-shkodenko commented
Решение не соответвует принципам SOLID и нуждается в обновлении. Возможный подход к решению можно подсмотреть в моем репозитории. Этот подход я демонстрировал также на четвертой встрече в ходе анализа выполненеия третьего задания. Готов ответить на возникающие вопросы.

2021-04-26 16:37 UTC, StrangerM commented
Для класу BuyerBuilder добавив DI Container, для класу -MealBuilder - якщо добавити так само DI Container, то при виклику методу FillInList(string str) з класу BuyerBuilder  List<Meal> оновляється. Не знайшов як обійти це- тому використав Singleton паттерн.

2021-04-27 02:33 UTC, serhii-shkodenko requested changes

2021-04-27 02:33 UTC, serhii-shkodenko commented on Task2/BLL/ICreatable.cs
> +    public interface ICreatable
Це занадто загальний інтерфейс, подумай, чи він взагалі вартий існування.

2021-04-27 02:33 UTC, serhii-shkodenko commented on Task2/BLL/MealBuilder.cs
> +    public class MealBuilder : ICreatable, IRepository
Порушення Single responsibility principle. Класс робить забагато роботи: і містить логіку роботи із даними і виводить їх користувачу. Це потрібно розділити.

2021-04-27 02:33 UTC, serhii-shkodenko commented on Task2/BLL/BuyerBuilder.cs
> +    public class BuyerBuilder : ICreatable, IRepository
Порушення Single responsibility principle. Класс робить забагато роботи: і містить логіку роботи із даними і виводить їх користувачу. Це потрібно розділити.

2021-04-27 02:33 UTC, serhii-shkodenko commented on Task2/DI/DIContainer.cs
> +    class DIContainer
Не вистачає модифікатора доступу.

2021-04-27 02:33 UTC, serhii-shkodenko commented on Task2/DI/DIContainer.cs
> +        private readonly IRepository _service1;
Ім'я `_service1` потребує покращення, незрозуміло, що це за сервіс.

2021-04-27 15:28 UTC, StrangerM commented on Task2/BLL/ICreatable.cs
> +    public interface ICreatable
Interface was deleted

2021-04-27 15:29 UTC, StrangerM commented on Task2/BLL/BuyerBuilder.cs
> +    public class BuyerBuilder : ICreatable, IRepository
Added classes for validation and display data

2021-04-27 15:30 UTC, StrangerM commented on Task2/BLL/MealBuilder.cs
> +    public class MealBuilder : ICreatable, IRepository
Added classes for validation and display data

2021-04-27 15:30 UTC, StrangerM commented on Task2/DI/DIContainer.cs
> +    class DIContainer
added

2021-04-28 08:44 UTC, merged